image: node

stages:
 - lint
 - publish
 - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

eslint:
  stage: lint
  script:
    - npm install
    - npm install -g eslint
    - npm install eslint-config-standard
    - npm install eslint-plugin-import
    - npm install eslint-plugin-node
    - npm install eslint-plugin-promise
    - ./node_modules/eslint/bin/eslint.js .
  allow_failure: true

publish:
  image: docker:latest
  stage: publish
  variables:
  DOCKER_HOST: tcp://localhost:2375/
  script:
    - docker build -t $TAG_COMMIT -t $TAG_LATEST .
