version: '3.8'
services:

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.danshin.ms'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.danshin.ms'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '443:443'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
    networks:
      - gitlab

  gitlab-runner:
    image: 'gitlab/gitlab-runner:latest'
    restart: always
    depends_on:
      - gitlab
    volumes:
      - ../../../var/run/docker.sock:/var/run/docker.sock
      - ~/gitlab-runner-config:/etc/gitlab-runner
      - ~/cache:/cache
    networks:
      - gitlab

networks:
  gitlab:

#docker-compose -f "docker-compose.yml" up -d --build