image: node

stages:
 - lint

cache:
  paths:
    - node_modules/

before_script:
  - npm install
  - npm install -g eslint
  - npm install eslint-config-standard
  - npm install eslint-plugin-import
  - npm install eslint-plugin-node
  - npm install eslint-plugin-promise

eslint:
  stage: lint
  tags:
    - docker
  script:
    - ./node_modules/eslint/bin/eslint.js .
  allow_failure: true